package cli

import (
	"database/sql"
	"os"
	"path/filepath"
	"strings"
	"testing"

	_ "github.com/mattn/go-sqlite3"
)

func TestResolveCodeSource_CodeFlagTakesPrecedence(t *testing.T) {
	tests := []struct {
		name     string
		codeFlag string
		stdin    string
		want     string
		wantErr  bool
	}{
		{
			name:     "--code flag provided, stdin empty",
			codeFlag: "code from flag",
			stdin:    "",
			want:     "code from flag",
		},
		{
			name:     "--code flag provided, stdin also has content",
			codeFlag: "code from flag",
			stdin:    "code from stdin",
			want:     "code from flag",
		},
		{
			name:     "--code flag empty, stdin has content",
			codeFlag: "",
			stdin:    "code from stdin",
			want:     "code from stdin",
		},
		{
			name:     "--code flag empty, stdin empty",
			codeFlag: "",
			stdin:    "",
			wantErr:  true,
		},
		{
			name:     "--code flag whitespace only, stdin empty",
			codeFlag: "   ",
			stdin:    "",
			wantErr:  true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			stdin := strings.NewReader(tt.stdin)
			got, err := resolveCodeSource(stdin, tt.codeFlag)

			if tt.wantErr {
				if err == nil {
					t.Error("expected error but got none")
				}
				return
			}

			if err != nil {
				t.Errorf("unexpected error: %v", err)
				return
			}

			if got != tt.want {
				t.Errorf("got %q, want %q", got, tt.want)
			}
		})
	}
}

func TestRunSave_UsesCustomDBPath(t *testing.T) {
	tempDir := t.TempDir()
	customDBPath := filepath.Join(tempDir, "nested", "custom.db")

	opts := &CLIOptions{
		DBPath: customDBPath,
		Stdin:  strings.NewReader(""),
	}

	if err := runSave(opts, "Test Snippet", "go", "test,unit", "fmt.Println(\"x\")"); err != nil {
		t.Fatalf("runSave returned error: %v", err)
	}

	if _, err := os.Stat(customDBPath); err != nil {
		t.Fatalf("expected custom DB path to exist, stat failed: %v", err)
	}

	db, err := sql.Open("sqlite3", customDBPath)
	if err != nil {
		t.Fatalf("failed opening custom db: %v", err)
	}
	defer db.Close()

	var count int
	if err := db.QueryRow("SELECT COUNT(*) FROM snippets").Scan(&count); err != nil {
		t.Fatalf("query failed: %v", err)
	}
	if count != 1 {
		t.Fatalf("expected 1 snippet, got %d", count)
	}
}

func TestRunSave_ValidationFailure(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "test.db")
	opts := &CLIOptions{
		DBPath: dbPath,
		Stdin:  strings.NewReader(""),
	}

	err := runSave(opts, "Test", "go", "tags", "")
	if err == nil {
		t.Fatal("expected error for empty code")
	}
	if !strings.Contains(err.Error(), "code content required") {
		t.Fatalf("expected code content error, got: %v", err)
	}
	if _, statErr := os.Stat(dbPath); !os.IsNotExist(statErr) {
		t.Fatalf("expected DB file to not be created on validation failure")
	}
}

func TestRunSave_InvalidTag(t *testing.T) {
	opts := &CLIOptions{
		DBPath: filepath.Join(t.TempDir(), "test.db"),
		Stdin:  strings.NewReader(""),
	}

	err := runSave(opts, "Test", "go", "invalid tag!", "test code")
	if err == nil {
		t.Fatal("expected invalid tag error")
	}
}

func TestRunSave_AutoGeneratedTitle(t *testing.T) {
	opts := &CLIOptions{
		DBPath: filepath.Join(t.TempDir(), "test.db"),
		Stdin:  strings.NewReader(""),
	}

	err := runSave(opts, "   ", "go", "tags", "test code")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
